### ISSUE TITLE
Old Lyrics show up on the left without margin

### ISSUE THREAD

**Issue by MCUxDaredevil** [SpotX-Official/SpotX#485]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.19.941.gbf202593
- Windows: Windows 11 22H2 22621.2215
- PowerShell: 7.3.6
```

### 📝 Description

1. Have the -old_lyrics feature installed
2. Play any song
3. Open the lyrics window
 
The lyrics are left aligned without any margin making it look very weird
A lot of songs have it bugged but some have it normal

### 📸 Screenshots

![image](https://github.com/amd64fox/SpotX/assets/59441946/0faede2c-9f1a-4cc0-9939-8bf8da80677e)

![image](https://github.com/amd64fox/SpotX/assets/59441946/a48a556c-5d53-4ac2-9ee3-f634493e0529)

**Comment by amd64fox** [comment]
although this is not a SpotX bug but a native client bug, it seems they have made some CSS errors

could you add these lines to the xpui.css file? 
need to test how it works

```css
.Q2RPoHcoxygOoPLXLMww {
    display: grid;
}

Q2RPoHcoxygOoPLXLMww .esRByMgBY3TiENAsbDHA {
    margin: 0 64px;
}

@media(min-width:1024px) {
    .Q2RPoHcoxygOoPLXLMww .esRByMgBY3TiENAsbDHA {
        margin: 0 144px
    }
}
```
